.github/workflows/realm-flutter-android.yml
.github/workflows/realm-flutter-ios.yml

Seems like macos-latest switched to 11 and Android CI started to fail sporadically. Previously on Mac 10.15 it was running deterministically so use that one instead

use macos 10.15 for gh actions

---

lib/src/cli/metrics/metrics.dart

Don't report language version in language field, ie. report 'dart', not 'dart 2.14.0'

Language should just be 'dart'

---

lib/src/list.dart
lib/src/native/realm_core.dart
test/realm_test.dart

RealmList.Clear implemented. Clears collection objects relations but not the objects themselves. (#58)

RealmList.clear

---

test/realm_test.dart

Query results tests into a group
Added test for query with no values for arguments.
Added test for query with wrong arguments values types.
Fixes #193

Query results tests for arguments

---

generator/lib/src/field_element_ex.dart
generator/test/generator_test.dart

- Fixed.. may allow bools to be indexed later, even if it makes little sense (dotnet supports it)

disallow bool as index and primary key

---

lib/src/realm_class.dart

This fixes `realm.find<T>(String primaryKey)` to take object instead `realm.find<T>(Object primaryKey)`

find should take object

---

build.yaml
example/myapp/build.yaml
example/myapp/pubspec.yaml
flutter/realm_flutter/build.yaml
flutter/realm_flutter/example/pubspec.yaml
flutter/realm_flutter/pubspec.yaml
lib/src/cli/generate/options.g.dart
pubspec.yaml

This enables realm object generation after realm package is added to user project.
include build.yaml for realm_dart and realm package
removes dart example  build.yaml
leaves build.yaml for flutter example as an example for customized build.yaml
move build_runner as a dependency
This substitutes #211

Support realm object generation by default

---

README.md
example/myapp/bin/myapp.dart
example/myapp/bin/myapp.g.dart
flutter/realm_flutter/example/lib/main.dart
lib/src/realm_class.dart
test/realm_test.dart

Fixes premature realm close in Flutter
Also update example to not include primarykeys to support multiple re-runs

Fix premature realm close on Flutter

---

CHANGELOG.md
generator/CHANGELOG.md

fixes weird chars in readme.
The `E` in `ComplEtely ` is not ansi but utf-8.

fix non ANSI chars

---

flutter/realm_flutter/macos/realm.podspec

Ensure binary placeholder file exists before the build is started on macos

ensure macos binary placeholder file exists

---

CHANGELOG.md
lib/src/list.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/results.dart
test/realm_test.dart

Add query method to RealmList class

Realm list.query

---

README.md

clarify readme

---

.github/workflows/realm-dart-linux.yml
.github/workflows/realm-dart-macos.yml
.github/workflows/realm-dart-windows.yml
.github/workflows/realm-flutter-android.yml
.github/workflows/realm-flutter-ios.yml
.github/workflows/realm-flutter-macos.yml
.github/workflows/realm-flutter-windows.yml
.github/workflows/realm-generator.yml

Now that we have randomized tests we should use every opportunity to run CI

run CI on every change

---

CHANGELOG.md
lib/src/configuration.dart
lib/src/native/realm_core.dart
test/configuration_test.dart

Implemented inMemory property of realm configuration. Fixes #91

config inMemory

---

CHANGELOG.md
lib/src/realm_class.dart
test/realm_test.dart

Fixes https://github.com/realm/realm-dart/issues/442
The `Transaction` class is currently undocumented as we don't have explicit `beginWrite` method. We may introduce it at a later point, especially once we get async writes.
I made `isInTransaction` public because it's quite useful when you are calling methods from inside your write transaction. Since starting a second transaction will throw, we should expose a mechanism for developers to guard against it. Example:
```dart
void markComplete(Task task) {
if (task.realm.isInTransaction) {
task.isComplete = true;
} else {
task.realm.write(() {
task.isComplete = true;
});
}
}
```

Fix write inside write rollback; expose Realm.isInTransaction

---

CHANGELOG.md
lib/src/configuration.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
test/configuration_test.dart
test/realm_test.dart

This is a POC that delays constructing the native config until we actually get to open the Realm instance.
I think this is a cleaner approach for passing more complex data to native. We can use it for all config types (realm, sync, app) as well as for credentials.

Delay constructing the config handle

---

common/lib/realm_common.dart
common/lib/src/realm_types.dart
common/pubspec.yaml
generator/lib/src/dart_type_ex.dart
generator/lib/src/field_element_ex.dart
generator/test/good_test.dart
generator/test/good_test_data/all_types.dart
generator/test/good_test_data/all_types.expected
generator/test/good_test_data/primary_key.dart
generator/test/good_test_data/primary_key.expected
generator/test/test_util.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
test/realm_object_test.dart
test/realm_object_test.g.dart

support objectId
use custom line by line matcher for generator tests
this supersedes https://github.com/realm/realm-dart/pull/460
fixes #461

add support for objectId

---

lib/src/configuration.dart
lib/src/native/realm_core.dart
test/configuration_test.dart

Adds a return value to the should compact callback as it was previously void and the Realm was indiscriminately compacted regardless of what the user returned. Additionally, adds more comprehensive tests for the feature.

Fix shouldCompact callback

---

CHANGELOG.md
lib/src/app.dart
lib/src/native/realm_core.dart

support remove user

---

.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml

This is only needed so that the workflows end up in `master`. The actual implementation will follow later.

Add new workflows for prepare/publish release

---

.github/workflows/ci.yml

This adds an extra cache step to the native builds that allows us to completely skip the build if we found the binary in the cache.
It speeds up builds noticeably when nothing in `./src` changes, otherwise it falls back to normal builds.

Cache complete binary builds

---

CHANGELOG.md
lib/src/native/realm_core.dart
test/realm_object_test.dart
test/realm_object_test.g.dart

Fixes boolean value persistence
fixes #474

Fix boolean

---

.github/workflows/cleanup-clusters.yml

This is a manual dispatch nuclear workflow that wipes everything in the project - we should only use it rarely as the cleanup job should already be taking care of this.

Add a workflow to delete clusters and apps

---

.github/workflows/ci.yml
.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
.gitignore
common/pubspec.yaml
flutter/realm_flutter/linux/CMakeLists.txt
generator/pubspec.yaml
generator/test/test_util.dart
lib/src/cli/archive/archive_command.dart
lib/src/cli/install/install_command.dart
lib/src/init.dart
pubspec.yaml

This implements a workflow that uploads binaries to S3 and optionally to pub.dev. It roughly does the following:
* Prepare packages:
1. Downloads binaries from PR build
1. Infers the version
a. [Prod] version is equal to whatever is in pubspec.yaml
a. [Staging] version is equal to whatever is in pubspec.yaml + commit sha
1. Runs the `archive` command to produce the platform-specific archives
1. Updates all references to `realm_common` and `realm_generator`
a. [Prod] those point to the upcoming version
a. [Staging] those point to `../realm_common` and `../realm_generator`
1. Removes `publish_to: none ` from all packages
1. Prepares the various packages in their respective folders and runs `dart pub publish --dry run` on those
1. Uploads the release folder containing all the packages as …

Prepare a workflow for publishing releases

---

CHANGELOG.md
lib/src/app.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
test/app_test.dart

Sync Client Config: set log level. Fixes #372 
Sync Client Config: support connection timeout. Fixes #376

App config log level and request timeout

---

.github/workflows/ci.yml

This fixes a small error in the generator coverage on CI. We forgot to disable the upload step while we disabled the generator

fix generator coverage error on CI

---

CHANGELOG.md
lib/src/native/realm_core.dart
test/realm_object_test.dart
test/test.dart
test/test.g.dart

add datetime support

---

.vscode/settings.json
common/lib/src/realm_types.dart
ffigen/sync_session.h
lib/src/app.dart
lib/src/cli/deployapps/baas_client.dart
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/session.dart
lib/src/subscription.dart
lib/src/user.dart
src/CMakeLists.txt
src/sync_session.cpp
src/sync_session.h
test/app_test.dart
test/session_test.dart
test/test.dart
test/test.g.dart

This adds support for most session API. Currently covered are:
Remaining for a follow up PR are:

Add support for SyncSession

---

CHANGELOG.md
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/session.dart
test/session_test.dart

This adds support for connection state change notifications on the sync session and extends the session user test.
Fixes https://github.com/realm/realm-dart/issues/596
Fixes https://github.com/realm/realm-dart/issues/595

Add support for remaining session API

---

ffigen/config.yaml
ffigen/sync_client.h
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
src/CMakeLists.txt
src/sync_client.cpp
src/sync_client.h
src/sync_session.cpp
test/subscription_test.dart
test/test.dart

Add missing trampoline, and copy error messages before bouncing.
* Copy error message native, and free on dart side
* Add trampoline for realm_sync_config_set_error_handler
Fixes:  #630

Add missing trampoline

---

src/realm_dart.cpp

It is legal for http body to contain null bytes.

Revert but.body assignment

---

.github/workflows/ci.yml
lib/src/cli/deployapps/baas_client.dart
lib/src/cli/deployapps/deployapps_command.dart
lib/src/cli/deployapps/options.dart
lib/src/cli/deployapps/options.g.dart
test/session_test.dart
test/test.dart

This modifies the PR workflow to use a single cluster with multiple applications. Each application uses its own database, so they should not be clashing with each other.

Use only one cluster for tests

---

lib/src/native/realm_bindings.dart
src/realm_dart_sync.cpp

Pulls in the fix from Core that introduces a sleep between polling when no sessions are active (https://github.com/realm/realm-core/pull/5594).

Update to latest Core

---

.github/workflows/ci.yml

This is building on top of https://github.com/realm/realm-dart/pull/663 by moving the deploy/cleanup steps to separate jobs. This shaves 45-60 seconds from the test jobs and those typically complete by the time the build-native job completes, so tests are ready to run in about a  minute.
The reason why this works is twofold:
1. We can split the deploy-apps job because our tests do not rely on it. The test runner will import the apps if necessary, so in the event of a re-run of the failed job, the test runner will fail to find the apps and import them itself.
2. We can split the cleanup-apps job because re-running a failed job will also re-run its dependents. In the event of a re-run, the cleanup will still be executed with the run attempt, so it will delete apps created by the test …

Use a matrix to deploy and cleanup apps

---

CHANGELOG.md
lib/src/app.dart
lib/src/native/realm_core.dart
test/app_test.dart

support App.deleteUser

---

CHANGELOG.md
lib/src/credentials.dart
lib/src/native/realm_core.dart

- Implement support for Apple, Facebook and Google based authentication

Apple, Facebook and Google authentication

---

lib/src/cli/common/archive.dart
lib/src/list.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/realm_object.dart
test/dynamic_realm_test.dart

Adds a string-based API to read properties of a RealmObject. Right now we only support reading as that's required to get migrations working, but it can be extended in the future to also support setting.
```dart
final obj = realm.dynamic.find("Foo", 123);
// Get simple primitive
final str = obj.dynamic.get<String>("stringProp");
// Get another object
final bar = obj.dynamic.get<RealmObject>("bar");
final barString = bar.dynamic.get<String>("stringProp");
// Get a list of objects
final bars = obj.dynamic.getList<RealmObject>("bars");
// Iterate the list as normal
for (final bar in bars) {
print(bar.dynamic.get<DateTime>("dateProp");
}
```
Additionally, implements `noSuchMethod` on `RealmObject` in order to support dynamic invocation:
```dart
dynamic obj = realm.dynamic.find("Foo", 123);
// …
```

Add support for string based/dynamic API on RealmObject

---

lib/src/list.dart
lib/src/native/realm_core.dart
test/list_test.dart

Apparently we never wired up and tested `removeAt`.
This fixes #883

Fix removeAt

---

LICENSE
README.md

This should allow the pana tool to pickup on the license type and grant us another 10 pub points on pub.dev.
LICENSE now only contains the actual Apache 2 license, and the mini export compliance clause is removed from README.md too.
It also fixes #658

Remove export compliance from LICENSE (and README.md)

---

.github/workflows/prepare-release.yml
lib/src/init.dart
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
src/realm_dart.cpp
src/realm_dart.h

Stamps library version into both dart and native code when preparing
release.
Compare the version when opening the library and throw a descriptive
exception if they don't match.

Validate dynamic library version on Startup

---

CHANGELOG.md
example/bin/myapp.g.dart
flutter/realm_flutter/example/lib/main.g.dart
generator/lib/src/realm_model_info.dart
generator/test/good_test.dart
generator/test/good_test_data/all_types.expected
generator/test/good_test_data/list_initialization.expected
generator/test/good_test_data/mapto.expected
generator/test/good_test_data/optional_argument.expected
generator/test/good_test_data/pinhole.expected
generator/test/good_test_data/primary_key.expected
generator/test/good_test_data/required_argument.expected
generator/test/good_test_data/required_argument_with_default_value.expected
generator/test/good_test_data/user_defined_getter.expected
lib/src/list.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/realm_object.dart
lib/src/results.dart
test/list_test.dart
test/realm_object_test.dart
test/realm_object_test.g.dart
test/realm_test.dart
test/results_test.dart
test/test.dart
test/test.g.dart

Adds support for freezing Realms and entities:
```dart
final liveRealm = Realm(Configuration.local([...]));
final frozenRealm = liveRealm.freeze();
expect(frozenRealm.isFrozen, true);
final frozenResults = liveRealm.all<Foo>().freeze();
expect(frozenResults.isFrozen, true);
final frozenObject = liveRealm.find<Foo>(123).freeze();
expect(frozenObject.isFrozen, true);
final frozenList = liveRealm.find<Foo>(123).bars.freeze();
expect(frozenList.isFrozen, true);
```
Fixes https://github.com/realm/realm-dart/issues/56
Fixes https://github.com/realm/realm-dart/issues/54
Fixes https://github.com/realm/realm-dart/issues/55
Fixes https://github.com/realm/realm-dart/issues/808
Fixes https://github.com/realm/realm-dart/issues/807
Fixes https://github.com/realm/realm-dart/issues/806

Add support for frozen Realms

---

.github/workflows/ci.yml
CHANGELOG.md
flutter/realm_flutter/tests/test_driver/realm_test.dart
generator/lib/src/class_element_ex.dart
generator/lib/src/field_element_ex.dart
generator/lib/src/realm_field_info.dart
generator/lib/src/realm_model_info.dart
generator/test/good_test_data/all_types.expected
generator/test/good_test_data/primary_key.expected
generator/test/good_test_data/required_argument.expected
lib/src/configuration.dart
lib/src/migration.dart
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/realm_object.dart
test/migration_test.dart
test/migration_test.g.dart
test/realm_object_test.dart
test/realm_object_test.g.dart
test/test.g.dart

Adds support for providing a migration callback in local configs.
Supersedes https://github.com/realm/realm-dart/pull/494.
Fixes https://github.com/realm/realm-dart/issues/70

Add support for migrations

---

CHANGELOG.md
lib/src/list.dart
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/realm_object.dart
test/list_test.dart

Implement indexOf using realm_list_find

---

CHANGELOG.md
lib/src/native/realm_core.dart

`realm_string_t` should never have been 0-terminated because it knows its own length. In fact, adding an extra empty byte will result in `\u0000` being appended at the end of the string. I don't know how to test this since the only place it's used currently is for the password, but I've verified it manually by looking at the http request body.

Remove extra byte in realm_string_t conversion

---

CHANGELOG.md
lib/src/list.dart
test/list_test.dart

Use indexOf in managed list remove

Efficient list remove

---

CHANGELOG.md
generator/lib/src/dart_type_ex.dart
generator/lib/src/realm_field_info.dart
lib/src/realm_object.dart
test/list_test.dart
test/test.dart
test/test.g.dart

Allow list of nullable primitives in realm models, such as:
```dart
@RealmModel()
class _Player {
@PrimaryKey()
late String name;
final scoresByRound = <int?>[]; // null means player didn't finish
}
```
Fixes #163 (supersedes  #708)

Implement list of nullables with minimal refactorings

---

CHANGELOG.md

the data api doesn't use token-based authentication ([docs](https://www.mongodb.com/docs/atlas/app-services/data-api/generated-endpoints/#std-label-data-api-authenticate))

Fix CHANGELOG Data API inaccuracy

---

lib/src/realm_class.dart

Export `Migration` and `MigrationCallback` so that they show up in the generated reference docs.

Export migration class and callback function

---

.github/workflows/check-changelog.yml
CHANGELOG.md

Fixes https://github.com/realm/realm-dart/issues/939
Example failure: https://github.com/realm/realm-dart/actions/runs/3192287922/jobs/5209591627
To disable the check, add `no-changelog` label.

Add an action to enforce changelog

---

.github/workflows/update-samples.yml

Fix getting release-version.outputs parameter.
Added `$` before `{{steps.release-version.outputs.release }}` to evaluate.
Fixes #956

Fix CI update samples workflow

---

CHANGELOG.md
lib/src/cli/generate/generate_command.dart

Fix `dart run realm_dart generate` command to exit with an error code when generation fails.
Otherwise, it does not terminate the execution of the command batch.
The CI for generating models for the samples after the new realm is released didn't fail on generating error.
Fixes #956

Exit with an error code when generate command fails.

---

.github/workflows/auto-assign.yml
.github/workflows/binary-combine-android.yml
.github/workflows/binary-combine-ios.yml
.github/workflows/build-native.yml
.github/workflows/check-changelog.yml
.github/workflows/ci.yml
.github/workflows/dart-desktop-tests.yml
.github/workflows/flutter-desktop-tests.yml
.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml

CI actions commit versions updated.
- Issue https://github.com/futureware-tech/simulator-action/issues/249.
- Waiting for https://github.com/pozetroninc/github-action-get-latest-release/issues/23 to be resolved.
Fixes #966

CI actions - fixed Node16

---

flutter/realm_flutter/pubspec.yaml
lib/src/cli/metrics/metrics.g.dart
pubspec.yaml

Increase json_annotation version to ^4.7.0.
Regenerate metrics.g.dart

Bump json_annotation version to fix generator tests

---

lib/src/cli/metrics/metrics.g.dart
test/test.dart
test/user_test.dart

I don't think we have an issue for this, but took a stab at adding some retry logic to our API key tests.

Improve robustness of API key tests

---

.vscode/launch.json
generator/README.md
generator/lib/src/class_element_ex.dart
generator/lib/src/field_element_ex.dart
generator/test/test_util.dart

print the exception stacktrace if generator encounters an exception
throw on no expected file found. - previously if an expected file was not found the test did succeed. This is not ideal since the file might be there with the wrong name giving a false impression that the test succeeds or not there at all.
generator tests are named after the exact file name. - previously the underscore was removed. This mostly helps when filtering the test runs in the console

Generator fixes

---

test/user_test.dart

This should fix our newly failing tests.

Don't assume api key order in fetchAll

---

CHANGELOG.md
lib/src/credentials.dart
lib/src/native/realm_core.dart
test/credentials_test.dart

- Returned `user.provider` was wrong for facebook, google and apple. All the other providers were correct, because their numbers remains the same.
- When we login with `Credentials.anonymous(reuseCredentials: false)` the returned user.provider is also `AuthProviderType.anonymous` instead of `anonymousNoReuse`. To be discussed.
Fixes  #992

Reorder AuthProviderType values

---

CHANGELOG.md
lib/src/native/realm_core.dart

Noticed that while looking at https://docs.google.com/document/d/17cqTiriugPEJQjvk58t7kwcr9Cdkat5Le7khJOZju5k/edit#. Need to write some tests for it though.

Set the correct schema mode for disconnectedSync

---

CHANGELOG.md
common/lib/src/realm_common_base.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/realm_object.dart
lib/src/util.dart
test/embedded_test.dart

This is a follow up on the embedded objects PR that I pulled to a separate branch because it depends on https://github.com/realm/realm-core/pull/5960.

Expose embeddedObject.getParent

---

lib/src/configuration.dart
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
src/realm_dart.cpp
src/realm_dart.h
src/realm_dart.hpp
src/realm_dart_sync.cpp
src/realm_dart_sync.h

Refactor client reset

---

CHANGELOG.md
common/lib/src/realm_types.dart
test/subscription_test.dart

- Add compensatingWrite error to SyncSessionErrorCode.
Fixes #1024

SyncSessionErrorCode.compensatingWrite(231)

---

CHANGELOG.md
common/lib/src/realm_types.dart
lib/src/configuration.dart

Set missing SyncError codes to Unknown

---

CHANGELOG.md
lib/src/cli/install/install_command.dart

This avoid conflict between users on the same machine.
Fixes #1060

Use random tmp destination for download

---

CHANGELOG.md
common/lib/src/realm_types.dart
generator/lib/src/dart_type_ex.dart
generator/lib/src/field_element_ex.dart
generator/lib/src/realm_field_info.dart
generator/lib/src/realm_model_info.dart
generator/test/error_test_data/not_an_indexable_type.expected
generator/test/error_test_data/nullable_realm_value.dart
generator/test/error_test_data/nullable_realm_value.expected
generator/test/error_test_data/realm_value_not_allowed_as_primary_key.dart
generator/test/error_test_data/realm_value_not_allowed_as_primary_key.expected
generator/test/good_test_data/all_types.dart
generator/test/good_test_data/all_types.expected
generator/test/good_test_data/indexable_types.dart
generator/test/good_test_data/indexable_types.expected
lib/src/list.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/realm_object.dart
test/indexed_test.dart
test/realm_value_test.dart
test/realm_value_test.g.dart

Support `RealmValue` that allows users to store different types in the same field
```dart
@RealmModel()
class _AnythingGoes {
@Indexed()
late RealmValue any;
late List<RealmValue> manyAny;
}
void main() {
final realm = Realm(Configuration.local([AnythingGoes.schema]));
final something = realm.write(() => realm.add(AnythingGoes(any: RealmValue.string('text'))));
realm.write(() {
something.manyAny.addAll([null, true, 'text', 42, 3.14].map(RealmValue.from));
});
}
```
Resolves: #684

Support RealmValue (aka mixed)

---

.github/workflows/build-native.yml
CHANGELOG.md
CMakePresets.json
lib/src/native/realm_bindings.dart

Rip-out vcpkg (use openssl + zlib prebuilds instead)

---

CHANGELOG.md
flutter/realm_flutter/tests/pubspec.yaml
generator/lib/src/pseudo_type.dart
generator/pubspec.yaml

Update to analyzer 5+

---

CHANGELOG.md
flutter/realm_flutter/android/build.gradle
flutter/realm_flutter/ios/realm.podspec
flutter/realm_flutter/linux/CMakeLists.txt
flutter/realm_flutter/macos/realm.podspec
flutter/realm_flutter/windows/CMakeLists.txt
lib/src/cli/common/target_os_type.dart
lib/src/cli/install/install_command.dart
lib/src/cli/install/options.dart
lib/src/cli/install/options.g.dart
lib/src/native/realm_core.dart

- Avoid opening plugin lib when running `flutter test`
- Allow running `dart run realm install` in flutter project to install realm lib for unit tests
- Use new --flavor flag
Fixes #791, fixes #870

Support unit tests with realm in Flutter projects

---

CHANGELOG.md
lib/src/app.dart
lib/src/native/realm_core.dart
test/app_test.dart

Expose the ability to reconnect all syncSessions in one go with `App.reconnect`.
Typical use would be to reconnect when a NIC change state, fx using the `connectivity_plus` package:
```dart
Connectivity().onConnectivityChanged.listen((event) {
if (event != ConnectivityResult.none) {
app.reconnect();
}
});
```
Fixes: #383

add App.reconnect

---

CHANGELOG.md
lib/src/configuration.dart
lib/src/session.dart
test/session_test.dart

`SyncResolveError` enum improvement. 
Added error code numbers according to the codes in C-API - https://github.com/realm/realm-core/pull/6186

Fix SyncResolveError values

---

CHANGELOG.md
lib/src/collections.dart
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
test/embedded_test.dart
test/list_test.dart
test/realm_set_test.dart

CollectionChanges cleared notification

---

.gitignore
CHANGELOG.md
flutter/realm_flutter/.pubignore
flutter/realm_flutter/example/macos/Podfile
flutter/realm_flutter/example/macos/Runner.xcodeproj/project.pbxproj
flutter/realm_flutter/macos/librealm_dart.dylib
flutter/realm_flutter/macos/realm.podspec
flutter/realm_flutter/tests/macos/Podfile
flutter/realm_flutter/tests/macos/Runner.xcodeproj/project.pbxproj
lib/src/init.dart

This lets CocoaPods set up the correct linking and code signing steps in Xcode.
Fixes #1153

[Flutter] package the dylib as a vendored library

---

.github/workflows/check-changelog.yml
.github/workflows/update-samples.yml

Related to #971
To avoid CI warnings we are update actions to use Node 16 and action-core@1.10.0
Only `coverallsapp` action is not updated and causes two warnings.

Bump github-actions commits sha

---

.github/workflows/ci.yml

This makes it so existing workflows runs are canceled when a new workflow starts for the same branch.

Cancel in-flight workflows when a commit is pushed

---

CHANGELOG.md
lib/src/configuration.dart
lib/src/native/realm_core.dart
test/app_test.dart
test/configuration_test.dart

Support flx sync compact callback

---

lib/src/cli/atlas_apps/baas_client.dart
test/app_test.dart
test/realm_test.dart
test/subscription_test.dart
test/test.dart
test/user_test.dart

Hides throws from 'package:test/expect.dart'.
Critical for main branch.
Disable test "Realm path with unicode symbols" for Android and IOS.
Fix job status in case of error while creating the App services

Fix test packages ambiguous `throws`

---

lib/src/cli/install/install_command.dart
lib/src/cli/install/options.dart
lib/src/cli/install/options.g.dart

This allows us to force install the shared library even if we would
normally skip it. This is useful if you wan't to run tests against a
released version without actually building the realm again.

Add a force flag to install

---

test/app_test.dart

Reversing the _join_ so that no-trace won't pass the test

Iterate over expected values and compare with actual values, not vice versa

---

CHANGELOG.md
lib/src/native/realm_core.dart
lib/src/realm_class.dart
src/realm_dart_logger.cpp

Removes `_RealmLogger` wrapper. 
Reminder to all: We should really be careful not to implement classes from dependencies unless we are sure we can't be broken by a minor dependency update.

remove _RealmLogger wrapper

---

CHANGELOG.md
lib/src/results.dart
test/list_test.dart
test/realm_set_test.dart
test/results_test.dart

Deprecate `isCleared` for `RealmResults`.
Fixes #1189
Related to https://github.com/realm/realm-dart/issues/1278

RealmResultsChanges.isCleared 

---

CHANGELOG.md
src/realm_dart_sync.cpp

- Ensure that caller always locks mutex first. Previously callee could theoretically get it first, causing the later condition wait to hang forever.
- Avoid double unlock which has undefined behaviour for pthread. Previously both an explicit call to unlock, and the destructor would unlock the mutex.
These issues where found while investigating #1328. 
fix #1328

Fix double unlock, and lock order race

---

CHANGELOG.md
src/realm_dart_sync.cpp

We do need the `completed` flag here to guard against spurious awake, such as can happen due to interrupts fx.
> When an unmasked, caught signal is delivered to a thread while the thread is waiting on a condition variable, then when the signal handler returns, the thread returns from the condition wait with a spurious wakeup (one not caused by a condition signal call from another thread).
https://docs.oracle.com/cd/E19683-01/806-6867/gen-24356/index.html
Still, we don't call the early `unique_lock::unlock` from [before](https://github.com/realm/realm-dart/pull/1335/files) as it would allow the `condition_variable::notify_one` to be called after `mutex` and `condition` is destroyed, if thread changes just after the unlock allowing calling thread to run function to completion.
This was …

Guard against spurious awakes

---

CHANGELOG.md
generator/lib/src/class_element_ex.dart

Calling
```dart
ElementDeclarationResult? getDeclarationFromElement(Element element) {
return session.resolvedLibrary.getElementDeclaration(element);
}
```
on a `ClassElement` is not guaranteed to return a result with a `node` of type `ClassDeclaration` (It can be a `ClassTypeAlias` as well), so the previous cast in `declarationAstNode` is not safe. However we don't actually only need a `AnnotatedNode` which is a common base for both `ClassDeclaration` and `ClassTypeAlias`.
Fix: #1285

Lossen cast

---

CHANGELOG.md
lib/src/session.dart

There are a number of reasons to prefer not to use broadcast stream here.
1. You can always turn a normal stream into a broadcast stream with `asBroadcast`, but it is impossible to go the other way.
2. We are not actually sharing the progress stream (and hence the backing `StreamController`). Each call to `getProgressStream` will create a new one anyway, so unless the user explicitly shares the returned stream there is no sharing. Fx. our own tests pass just fine, when converting to a normal stream.
3. The `SessionProgressNotificationController` owning the `StreamController` (and hence the `Stream`) is passed to native and become a GC root, preventing the GC to collect until realm-core releases it. Unlike single-subscriber streams which are constructed for one-time-use, a broadcast stream …

Avoid StreamController.broadcast

---

test/credentials_test.dart

`registerUser` fails before the tests, but is not really needed for these two tests

Fix email confirm with stale/invalid token tests

---

.github/workflows/dart-desktop-tests.yml

Temporarily use old Dart version for CI, until https://github.com/dart-lang/sdk/issues/53267 is fixed

use Dart 3.0.6 for linux CI

---

CHANGELOG.md
lib/src/native/realm_core.dart
lib/src/results.dart
test/results_test.dart

Add a `RealmResults.indexOf` using `realm_result_find` and implement `Iterable.contains` on top.
Fixes: #1393 
Fixes: #42

kn/results contains and indexOf

---

CHANGELOG.md
example/bin/myapp.g.dart
flutter/realm_flutter/example/lib/main.g.dart
generator/lib/src/realm_model_info.dart
generator/test/good_test.dart
generator/test/good_test_data/all_types.expected
generator/test/good_test_data/asymmetric_object.expected
generator/test/good_test_data/binary_type.expected
generator/test/good_test_data/embedded_annotations.expected
generator/test/good_test_data/embedded_objects.expected
generator/test/good_test_data/indexable_types.expected
generator/test/good_test_data/list_initialization.expected
generator/test/good_test_data/mapto.expected
generator/test/good_test_data/optional_argument.expected
generator/test/good_test_data/pinhole.expected
generator/test/good_test_data/primary_key.expected
generator/test/good_test_data/realm_set.expected
generator/test/good_test_data/required_argument.expected
generator/test/good_test_data/required_argument_with_default_value.expected
generator/test/good_test_data/user_defined_getter.expected
test/asymmetric_test.g.dart
test/backlinks_test.g.dart
test/indexed_test.g.dart
test/migration_test.g.dart
test/realm_object_test.g.dart
test/realm_set_test.g.dart
test/realm_value_test.g.dart
test/test.g.dart

Inspired by [issue](https://github.com/realm/realm-dart/issues/1412)

add 'ignore_for_file: type=lint' to *.g.dart files

---

CHANGELOG.md
lib/src/native/realm_core.dart
lib/src/realm_object.dart
test/realm_object_test.dart
test/subscription_test.dart

Fixes https://github.com/realm/realm-dart/issues/1418

Fix RealmObject.hashCode

---

lib/src/app.dart

Follow up on https://github.com/realm/realm-dart/pull/1378 to handle the case where the certificate is already present on the machine.

Handle duplicate certificates

---

lib/src/app.dart

This appears to have caused issues on Android where we would get certificate validation errors.

Use default context rather than creating a new one

---

CHANGELOG.md
generator/lib/src/realm_object_generator.dart

https://github.com/realm/realm-dart/pull/1438 introduced a regression where we would emit `// ignore_for_file: type=lint` for every file, even those that don't have any realm models, resulting in warnings like:
```
xyz.g.dart must be included as a part directive in the input library with:
part 'xyz.g.dart';
```
for files that don't contain models and should not have needed part files.

Don't emit code for empty files

---

CHANGELOG.md
lib/src/native/realm_core.dart
lib/src/realm_object.dart
test/app_test.dart
test/migration_test.dart

Fixes https://github.com/realm/realm-dart/issues/1448

Add MigrationRequiredException

---

lib/src/app.dart

This little bug causes cached apps to be retrieved with an baseUrl of `"null"` instead of `null`, when no explicit url is given.

Remember '?'

---

.vscode/launch.json
.vscode/settings.json
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/user.dart
src/dart-dl/dart_api.h
src/dart-dl/dart_api_dl.h
src/dart-dl/dart_native_api.h
src/dart-dl/dart_version.h
src/realm_dart_sync.cpp
src/realm_dart_sync.h
test/app_test.dart
test/user_test.dart

After the introduction of realm app caching hot-restart and background isolates no longer works reliably with realm.
Fixes: #1467 
Fixes: #1466
Fixes: #1451 
Fixes: #1433 (only half fixed by #1445)

Fix use of http transport from background isolate

---

flutter/realm_flutter/linux/CMakeLists.txt

This pull request fixes Flutter app build on Linux. Fix #1381.
The `execute_process` calls in `CMakeLists.txt` were broken. Neither `dart run realm install` nor `dart run realm metrics` were succeeding. Instead, they were returning `Could not find file 'realm'`.
Realm binaries were not being installed, thus provoking the error during the build.
This was solved by providing `WORKING_DIRECTORY` option to `execute_process`.

Fix Flutter app build on Linux

---

CHANGELOG.md
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
src/realm_dart.cpp
src/realm_dart.h

Always use persistent handles when passing dart objects as userdata to callbacks

---

CHANGELOG.md
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/user.dart
src/realm_dart_sync.cpp
src/realm_dart_sync.h
test/user_test.dart

Adds User.changes which allows developers to subscribe for notifications whenever the user changes.
Depends on https://github.com/realm/realm-core/pull/7302.

Expose User.changes

---

CHANGELOG.md
generator/lib/src/class_element_ex.dart

Fix a bug reported on slack for realm models with many properties, where the order of ctor arguments would appear random.
Turns out `List.sort` is not guaranteed to be stable (but apparently is for small lists).

Use a guaranteed stable sort

---

CHANGELOG.md
packages/realm_dart/lib/src/realm_object.dart
packages/realm_dart/test/dynamic_realm_test.dart
packages/realm_dart/test/list_test.dart
packages/realm_dart/test/realm_object_test.dart
packages/realm_dart/test/test.dart
packages/realm_dart/test/test.realm.dart

Replaces https://github.com/realm/realm-dart/pull/1305

Add support for dynamic.getSet/getMap

---

packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/test/realm_value_test.dart

Works except when reassigning collections to the same managed value, which depends on https://github.com/realm/realm-core/issues/7422.

RDART-941: Clear collections in mixed when reassigned

---

packages/realm_dart/lib/src/cli/install/install_command.dart

No changelog since we're not keeping dedicated entries for alpha releases.

RDART-976: Fix install command

---

.github/workflows/publish-release.yml
CHANGELOG.md
packages/realm/android/src/main/cpp/lib
packages/realm/ios/realm_dart.xcframework
packages/realm/linux/binary
packages/realm/windows/binary

Looks like the release workflow deleted a bunch of symlinks. Reverting this as well as adding a `git reset --hard` post package publish to make sure we're in a clean state.

Fix release workflow

---

melos.yaml
pubspec.yaml

- Use new steps feature (https://github.com/invertase/melos/pull/664)
- Drop analyze and format scripts, as these are now internal commands to melos
- Renamed format script to custom_format
- Renamed analyze:deps to lint:deps

Update melos to 5.2.0

---

CHANGELOG.md
packages/realm/macos/realm.podspec

The test to determine if a symlink should be added for development, was not correctly updated when we switched to side-by-side package layout. It worked fine in development, but would also try to setup dev symlink for macos lib on end-users machine

Wrong test for local development

---

CHANGELOG.md
packages/realm_dart/lib/src/native/realm_bindings.dart

RDART-989: Update realm-core to v14.4.1

---

CHANGELOG.md
packages/realm_generator/lib/src/field_element_ex.dart
packages/realm_generator/test/good_test_data/const_initializer.dart
packages/realm_generator/test/good_test_data/const_initializer.expected
packages/realm_generator/test/good_test_data/const_initializer.realm.dart

RDART-992: Const initializer evaluation is too simple

---

packages/realm_generator/lib/src/field_element_ex.dart
packages/realm_generator/test/good_test_data/const_initializer.dart
packages/realm_generator/test/good_test_data/const_initializer.expected

As mentioned in https://github.com/realm/realm-dart/issues/1606#issuecomment-2028498843 identifier expressions are not considered when establishing const-ness. This PR fixes that.

RDART-992: Handle Identifer expression as well

---

CHANGELOG.md
packages/realm_dart/lib/src/init.dart

This PR aims to give a better error message, if we fail to load the native shared library. 
In the process It changes how we attempt to open it.
First of all it only tries one place when running under the flutter vm, which is the most common scenario. This is not only more correct, but it also improves the error message on failure by not referring to unrelated paths.
Secondly, it will report a hint to add `realm` package if it fails. It is an easy mistake to only add `realm_dart`. We have seen one example already in #1595.
Fix: #1595 
```
dart run bin/init_realm_dart.dart
Unhandled exception:
Realm error : Could not open librealm_dart.dylib. Tried:
- "librealm_dart.dylib"
- "/Users/kasper/.puro/shared/caches/e76c956498841e1ab458577d3892003e553e4f3c/dart-sdk/bin/librealm_dart.dylib" …
```

 RDART-983: Refactor how we open dynamic library to give better error message

---

CHANGELOG.md
packages/realm_dart/test/backlinks_test.dart
packages/realm_dart/test/backlinks_test.realm.dart
packages/realm_generator/lib/src/realm_model_info.dart
packages/realm_generator/test/good_test_data/all_types.expected

Backlinks are computed values and cannot be deserialized, and shouldn't be serialized either. Especially since we don't handle cycles during serialization gracefully, and backlinks are guarenteed cycles.
Fix #1616

RDART-996: Don't serialize backlinks

---

CHANGELOG.md
packages/realm_generator/lib/src/field_element_ex.dart
packages/realm_generator/pubspec.yaml
packages/realm_generator/test/good_test_data/private_fields.dart
packages/realm_generator/test/good_test_data/private_fields.expected
packages/realm_generator/test/good_test_data/private_fields.realm.dart

RDART-852: Allow private fields on models

---

CHANGELOG.md
packages/realm_common/lib/src/realm_types.dart
packages/realm_dart/test/realm_value_test.dart

Minor optimization
base of #1632 
Fixes: #1634

RDART-1007: Compare 8 bytes at a time for Uint8Lists

---

CHANGELOG.md
packages/realm_common/lib/src/realm_types.dart
packages/realm_dart/test/realm_value_test.dart

RDART-1006: Reference equality implies equality

---

CHANGELOG.md
packages/realm_common/lib/src/realm_common_base.dart
packages/realm_common/lib/src/realm_types.dart
packages/realm_generator/lib/src/class_element_ex.dart
packages/realm_generator/lib/src/dart_type_ex.dart
packages/realm_generator/lib/src/realm_model_info.dart
packages/realm_generator/test/good_test_data/all_named_ctor.dart
packages/realm_generator/test/good_test_data/all_named_ctor.expected
packages/realm_generator/test/good_test_data/all_named_ctor.realm.dart
packages/realm_generator/test/good_test_data/private_fields.expected

Support per realm model configuration of the generator via the `GeneratorConfig` class. Currently we only support specifying the constructor style to use, as this has been a very frequent request (see #292).
```dart
// somewhere define your preferred generator configuration and a const RealmModel that uses it
const config = GeneratorConfig(ctorStyle: CtorStyle.allNamed);
const realmModel = RealmModel.using(generatorConfig: config);
@realmModel // <-- use here
class _Person {
late String name;
int age = 42;
}
```
will generate a constructor like:
```dart
Person({
required String name,
int age = 42,
}) { ... }
```
Fixes: #292
Fixes: #1642

RDART-1010: Allow configuration of generator per realm model class

---

CHANGELOG.md
melos.yaml
packages/ejson/pubspec.yaml
packages/ejson_analyzer/pubspec.yaml
packages/ejson_annotation/pubspec.yaml
packages/ejson_generator/pubspec.yaml
packages/ejson_lint/example/pubspec.yaml
packages/ejson_lint/pubspec.yaml
packages/realm/example/pubspec.yaml
packages/realm/pubspec.yaml
packages/realm/tests/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/example/pubspec.yaml
packages/realm_dart/pubspec.yaml
packages/realm_generator/pubspec.yaml

This is to avoid a few Dart compiler bugs related to Finalizable objects:
- https://github.com/dart-lang/sdk/issues/54414
- https://github.com/dart-lang/sdk/issues/52596
- https://github.com/dart-lang/sdk/issues/51538
Fixes: #1647

RDART-1014: Bump required sdk version to ^3.3.0

---

CHANGELOG.md
packages/realm/ios/Resources/PrivacyInfo.xcprivacy
packages/realm/ios/realm.podspec
packages/realm/macos/Resources/PrivacyInfo.xcprivacy
packages/realm/macos/realm.podspec

Adds privacy manifests to our iOS and macOS plugins.
While we only *need* to update the plugins listed [here](https://developer.apple.com/support/third-party-SDK-requirements/) for now (ie RealmSwift), the wording of the page:
> The following are commonly used SDKs in apps on the App Store
suggests that the list of things for which this is required is just an arbitrary cutoff rather than a conceptual distinction, so it seems safest to just assume the list will grow over time and do this for the realm flutter package as well. To be honest I don't trust that Apple got the list right.
Note that we are following the standard Flutter / Cocoapods implementation which has the following caveat:
> The large caveat is that we do not currently know if this actually works. This is the method of …

RDART-964: Add PrivacyInfo.xcprivacy for iOS and macOS

---

CHANGELOG.md
packages/realm_dart/lib/src/app.dart
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/test/app_test.dart
packages/realm_dart/test/baas_helper.dart
packages/realm_dart/test/test.dart

Updates nullability annotations - the getter should never return `null`, while the setter should accept `null` to indicate the developer wants to reset the base url to the default value.
Fixes https://github.com/realm/realm-dart/issues/1523.

RDART-950: Update nullability annotations for base url API

---

.github/workflows/ci.yml
CHANGELOG.md
packages/realm_dart/ffigen.yaml
packages/realm_dart/lib/src/native/realm_bindings.dart
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/test/app_test.dart
packages/realm_dart/test/realm_test.dart
packages/realm_dart/test/session_test.dart

RDART-1015: Update core to v14.6.2

---

CHANGELOG.md
packages/realm/ios/realm.podspec

Had a fruitful discussion with @tgoyne
This PR removes some cruft from our ios podspec pod_target_xcconfig
In particular 'VERSIONING_SYSTEM' => 'apple-generic'. 
This will cause a realm_privacy_vers.c file to be formed and hence an exe to be build, which will cause trouble on app store connect.
Fixes: #1656

RDART-1016: Cleanup iOS podspec

---

.github/workflows/build-native.yml
CHANGELOG.md
packages/realm_dart/test/app_test.dart
packages/realm_dart/test/credentials_test.dart
packages/realm_dart/test/user_test.dart

RDART-1034: Update realm-core to v14.7.0

---

.github/workflows/binary-combine-android.yml
.github/workflows/build-native.yml
.github/workflows/ci.yml
CHANGELOG.md
packages/realm_dart/CMakePresets.json
packages/realm_dart/dev/lib/src/build.dart
packages/realm_dart/scripts/build-android.sh
packages/realm_dart/src/realm_dart.cpp
packages/realm_dart/test/app_test.dart
packages/realm_dart/test/credentials_test.dart
packages/realm_dart/test/user_test.dart

Reduce android bundle size.
There is no need to build for `x86` as flutter itself does not support it.
Fixes: #1670

RDART-1022: Drop x86 as target

---

CHANGELOG.md
packages/realm_dart/lib/src/realm_class.dart
packages/realm_dart/lib/src/realm_object.dart
packages/realm_dart/test/dynamic_realm_test.dart
packages/realm_dart/test/test.dart
packages/realm_dart/test/test.realm.dart

Fixes https://github.com/realm/realm-dart/issues/1668
Additionally, had to add `Realm.dynamic.create` and `RealmObject.dynamic.set` to be able to test.
TODO:

RDART-1021: Wire up some basic dynamic setting and change notifications

---

CHANGELOG.md
packages/realm_dart/lib/src/scheduler.dart

 RDART-1028: Use Zone.current.bindUnaryCallbackGuarded for RawReceivePort.handler

---

CHANGELOG.md
packages/realm_dart/lib/src/app.dart
packages/realm_dart/lib/src/collections.dart
packages/realm_dart/lib/src/configuration.dart
packages/realm_dart/lib/src/credentials.dart
packages/realm_dart/lib/src/list.dart
packages/realm_dart/lib/src/map.dart
packages/realm_dart/lib/src/native/handle_base.dart
packages/realm_dart/lib/src/realm_class.dart
packages/realm_dart/lib/src/realm_object.dart
packages/realm_dart/lib/src/results.dart
packages/realm_dart/lib/src/session.dart
packages/realm_dart/lib/src/set.dart
packages/realm_dart/lib/src/subscription.dart
packages/realm_dart/lib/src/user.dart

To work-around https://github.com/dart-lang/sdk/issues/49643 we added `Finalizable` to all classes that contains `Handles`, and _pseudo_ `keepAlive` functions that was never actually called at runtime, but only existed to prevent early disposal.
As of Dart 2.19.0 this is no longer an issue, and since we require ^3.3.0 we can get rid of this code.
The following code illustrates the original problem:
```dart
import 'dart:ffi';
import 'dart:io';
typedef Free = NativeFunction<Void Function(Pointer)>;
final free = DynamicLibrary.process().lookup<Free>('free');
final _nativeFinalizer = NativeFinalizer(free);
class A implements Finalizable {
A() {
_nativeFinalizer.attach(this, Pointer.fromAddress(1), detach: this, externalSize: 1 << 32); // will crash, if it ever runs
}
}
class B implements …
```

RDART-1038: Drop keep alive hack

---

.github/workflows/binary-combine-android.yml
.github/workflows/build-native.yml
.github/workflows/ci.yml
.github/workflows/dart-desktop-tests.yml
.github/workflows/flutter-desktop-tests.yml
CHANGELOG.md
packages/realm_dart/CMakePresets.json
packages/realm_dart/scripts/build-macos.sh

Fixes: #1547 
- Use macos-14 runner for arm64 and macos-13 runner for x86_64 (see https://github.com/actions/runner-images?tab=readme-ov-file)
- Use xcode 15.4 which changes a bit how to build universal binaries.

RDART-962: Use xcode 15.4

---

.github/workflows/ci.yml
packages/realm_dart/lib/src/native/realm_bindings.dart
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/src/ios/platform.mm
packages/realm_dart/src/realm_dart.h
packages/realm_dart/test/test.dart

There has been a change that prevents a simple ulimit call on the macos host from taking effect on the simulator. Instead we expose `setrlimit` on `RealmCore` and call it from `setUpAll`.
Related to https://github.com/realm/realm-core/issues/7740
Fixes: #1702

RDART-1045: Expose setrlimit ios

---

CHANGELOG.md
packages/realm_dart/lib/src/cli/common/target_os_type.dart
packages/realm_dart/lib/src/cli/install/install_command.dart
packages/realm_dart/lib/src/cli/install/options.dart
packages/realm_dart/lib/src/cli/install/options.g.dart
packages/realm_dart/lib/src/init.dart
packages/realm_dart/lib/src/realm_dart.dart
packages/realm_dart/lib/src/realm_flutter.dart

This PR changes how the native lib is loaded under `flutter test`, `dart test`, and `dart run`.
It also changes how `realm install` command works.
Fixes: #1619

RDART-999: Fix flutter test dlopen

---

CHANGELOG.md
packages/realm_dart/test/results_test.dart

RDART-1052: Update realm-core to v14.9.0

---

.github/actions/setup-runner/action.yml
CHANGELOG.md
melos.yaml
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/cli/metrics/metrics_command.dart
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 3.0.0]

---

CHANGELOG.md
packages/ejson/lib/src/decoding.dart
packages/ejson/lib/src/encoding.dart
packages/ejson/pubspec.yaml
packages/ejson/test/ejson_test.dart
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/handles/native/from_native.dart
packages/realm_dart/lib/src/handles/native/to_native.dart
packages/realm_dart/test/indexed_test.dart

RDART-1059: Compensate for breaking change in sane_uuid

---

CHANGELOG.md
packages/realm_dart/lib/src/subscription.dart

Fixes https://github.com/realm/realm-dart/issues/1744

RDART-1069: Allow subscription set to be mocked

---

CHANGELOG.md
packages/realm_dart/lib/src/handles/native/config_handle.dart
packages/realm_dart/test/configuration_test.dart
packages/realm_dart/test/realm_test.dart
packages/realm_dart/test/test.dart

Change schema mode to additive explicit. When schema mode is .discovered, orphaned embedded objects are ignored, which causes a "no such table" exception to be called when we try to look up the table metadata.
Related to https://github.com/realm/realm-dart/issues/1740, but unlikely to have fixed it.

RDART-1066: Make schema mode for synchronized realms explicit

---

CHANGELOG.md
packages/realm_dart/lib/src/app.dart
packages/realm_dart/lib/src/configuration.dart
packages/realm_dart/lib/src/handles/native/app_handle.dart
packages/realm_dart/lib/src/handles/native/config_handle.dart
packages/realm_dart/lib/src/realm_class.dart
packages/realm_dart/test/app_test.dart
packages/realm_dart/test/baas_helper.dart

RDART-1081: Expose sync timeout options

---

CHANGELOG.md
packages/realm/android/build.gradle

Pull request #1773 exists but was not merged for more than a month due to some configuration mistakes concerned by cla-bot, making #1774 unsolved for long.
This pull request includes exactly the same things of what #1773 included, aiming to speed up the merging of this important update, so that the "android:attr/lStar not found" error can be fixed when using Flutter SDK 3.24.

RDART-1087: Update compileSdkVersion to fix android:attr/lStar not found

---

CHANGELOG.md
packages/CHANGELOG.ejson.md
packages/ejson_lint/lib/src/lints/mismatched_getter_type.dart
packages/ejson_lint/lib/src/lints/missing_getter.dart
packages/ejson_lint/lib/src/lints/too_many_annotated_constructors.dart
packages/realm_dart/lib/src/cli/metrics/metrics.g.dart
packages/realm_generator/lib/src/expanded_context_span.dart
packages/realm_generator/lib/src/pseudo_type.dart

The `PseudoType` extends the abstract class `TypeImpl` from the **analyzer** package. This makes it brittle in the face of interface changes to said class, which can occur without warning as the class is internal.
This PR tries to make it a little more "robust", by dodging compile time errors on changes to `TypeImpl`. This is done by implementing `noSuchMethod`. If any new members are added, we will no longer get a compile time error. 
We throw an exception, if the unexpected member is actually called, but that _should_ not happen as instances of `PseudoType` are only used internally by the **realm_generator**.
I think it is an acceptable compromise as this code will only ever run on the developers machine, when updating realm models. I think it is a better fix than #1814.
Fix: #1813

Fix PseudoType
