realm/realm-dart

lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/realm_object.dart
lib/src/realm_property.dart
test/realm_test.dart
test/realm_test.gen.dart

add property get/set support
add realm find by primary key support
add support for primary keys
fix tests cleanup speed

Add get, set, find by primary key

---

lib/src/native/realm_core.dart
lib/src/realm_class.dart
test/realm_test.dart

Realm.isClosed getter implemented (#52)

Realm isClosed getter implemented

---

lib/src/list.dart
lib/src/native/realm_core.dart
test/realm_test.dart

Reverts realm/realm-dart#152 so we can review it

Revert "RealmList.clear"

---

.github/workflows/realm-dart-macos.yml
.github/workflows/realm-flutter-android.yml
.github/workflows/realm-flutter-ios.yml

- Use macos-latest instead of macos-10.15 (https://github.com/actions/virtual-environments/issues/4060)

update macos runners

---

lib/src/realm_class.dart
test/realm_test.dart

- Rudimentrary implementation of Realm.addAll
- Add test

realm.addAll

---

lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/results.dart
test/realm_test.dart

- Add RealmResults<T>.query
- Add Realm.query<T>
- Support argument binding on queries

Add query support

---

test/realm_test.dart

Remove or re-enable some outcommented code

---

lib/src/list.dart
lib/src/native/realm_core.dart
test/realm_test.dart

Continue pull request #152  (issue #58)

realm list.clear

---

.github/workflows/realm-flutter-android.yml
lib/src/native/realm_core.dart

Validate all handles were created successfully.

Validate handle creation

---

lib/src/realm_class.dart
test/realm_test.dart

Implement Realm.exists - fixes #50

realm.exists and realm.existsSync

---

test/realm_test.dart

New test added for results.isEempty - fixes #38

results.isEmplty 

---

lib/src/realm_class.dart
test/realm_test.dart
test/realm_test.gen.dart

Results length tests implemented. Fixes #39

results.length

---

flutter/realm_flutter/windows/CMakeLists.txt
lib/src/cli/common/utils.dart

Windows flutter metrics

---

.github/workflows/realm-flutter-macos.yml
.github/workflows/realm-flutter-windows.yml
flutter/realm_flutter/macos/realm.podspec

metrics for macos flutter

---

.github/workflows/realm-dart-windows.yml

Fix archive on windows

---

flutter/realm_flutter/pubspec.yaml
pubspec.yaml

use range for tar dep

---

analysis_options.yaml
generator/analysis_options.yaml
generator/lib/src/meassure.dart

- Warn on missing documentation of public api
- Fix type error (missing int)

warn on missing api docs

---

CHANGELOG.md
README.md
common/CHANGELOG.md
common/README.md
common/pubspec.yaml
example/myapp/bin/myapp.dart
example/myapp/bin/myapp.g.dart
flutter/realm_flutter/CHANGELOG.md
flutter/realm_flutter/example/lib/main.dart
generator/CHANGELOG.md
generator/pubspec.yaml
lib/src/realm_class.dart
test/realm_test.dart

Prepare 0.2.0-alpha prerelease

Pre release

---

README.md
flutter/realm_flutter/android/build.gradle
flutter/realm_flutter/ios/realm.podspec
flutter/realm_flutter/macos/realm.podspec
flutter/realm_flutter/windows/CMakeLists.txt

This fixes running package commands on Flutter.

fix running package commands on flutter

---

CHANGELOG.md
README.md
common/CHANGELOG.md
common/README.md
common/pubspec.yaml
example/README.md
ffigen/pubspec.yaml
flutter/realm_flutter/CHANGELOG.md
flutter/realm_flutter/example/README.md
flutter/realm_flutter/example/pubspec.yaml
flutter/realm_flutter/ios/realm.podspec
flutter/realm_flutter/macos/realm.podspec
flutter/realm_flutter/pubspec.yaml
generator/CHANGELOG.md
generator/README.md
generator/pubspec.yaml
pubspec.yaml

prepare alpha release

---

.editorconfig
src/realm_dart_scheduler.cpp

- "Steal" .editorconfig settings for *.cpp, *.h, etc. from realm-dotnet repo
- Format all src/*.{h, cpp}

add editorconfig

---

.github/workflows/realm-dart-linux.yml
.github/workflows/realm-dart-macos.yml
.github/workflows/realm-dart-windows.yml
.github/workflows/realm-flutter-android.yml
.github/workflows/realm-flutter-ios.yml
.github/workflows/realm-flutter-macos.yml
.github/workflows/realm-flutter-windows.yml
.github/workflows/realm-generator.yml

Run generator tests on any changes to ./generator. Tests are run latest version of ubuntu, windows and macos, for both stable and beta.

Run generator test on CI

---

.github/workflows/realm-dart-linux.yml
.github/workflows/realm-dart-macos.yml
.github/workflows/realm-dart-windows.yml
.github/workflows/realm-generator.yml

CI realm dart tests randomized for Linux, Windows, Mac OS and realm generator

Randomize test execution ordering in CI

---

lib/src/cli/install/install_command.dart

Fix install command error message

---

CHANGELOG.md
lib/src/list.dart
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
src/realm_dart_collections.cpp
src/realm_dart_collections.h
test/realm_test.dart

This supersedes #206 
fixes #191

support list notifications

---

flutter/realm_flutter/pubspec.yaml
pubspec.yaml

Updated package "tar" to latest version. Fixes #272

updated tar package to latest

---

CONTRIBUTING.md

contributing.md file added

---

README.md
scripts/build-android.sh

fix android build dir

---

lib/src/native/realm_bindings.dart
scripts/build-ios.sh
scripts/build-macos.sh
scripts/build.bat
src/realm_dart.cpp
src/realm_dart_collections.cpp

Upgrade core to v11.12.0. https://github.com/realm/realm-core/commit/dcd3788f75bafb0cc397d145e1651aab3ad4bf0e

Upgrade core to v11.12.0

---

pubspec.yaml

Remove dependency_overrides for analyzer 3.3.1

Remove dependency override for analyzer

---

test/configuration_test.dart
test/list_test.dart
test/realm_object_test.dart
test/realm_test.dart
test/results_test.dart
test/test.dart

This takes care of automatically closing and deleting it

Use a helper to create a realm instance

---

.github/workflows/pr.yml

Run baas tests against QA rather than dev

Move baas tests to QA

---

.github/workflows/pr.yml
.gitignore
test/test.g.dart

This will fail the CI Build if there are uncommitted changes after the generator runs.

Fail generator tests if there are uncommitted changes

---

CHANGELOG.md
common/lib/realm_common.dart
common/lib/src/realm_types.dart
common/pubspec.yaml
generator/lib/src/dart_type_ex.dart
generator/lib/src/field_element_ex.dart
generator/test/good_test_data/primary_key.dart
generator/test/good_test_data/primary_key.expected
lib/src/native/realm_core.dart
lib/src/realm_class.dart
test/realm_object_test.dart
test/realm_object_test.g.dart

this supersedes #462 fixes #463

support uuids

---

common/lib/realm_common.dart
common/lib/src/realm_types.dart
common/pubspec.yaml
generator/lib/src/dart_type_ex.dart
generator/test/good_test_data/primary_key.dart
generator/test/good_test_data/primary_key.expected
lib/src/native/realm_core.dart
lib/src/realm_class.dart
test/realm_object_test.dart
test/realm_object_test.g.dart

Use sane_uuid package since its backing store is bytes and the public type is named Uuid

use sane_uuid package

---

CHANGELOG.md
lib/src/app.dart
lib/src/native/realm_core.dart

support switch user

---

flutter/realm_flutter/example/android/app/build.gradle
flutter/realm_flutter/pubspec.yaml
pubspec.yaml

http package should be a dep otherwise cli commands fail

move http package to a dep

---

test/credentials_test.dart
test/test.dart

fixes baas setup
skip baas setup for the current PID if already initialized.

fixes badass setup

---

lib/src/list.dart
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/results.dart
lib/src/subscription.dart
test/subscription_test.dart

- Update core to dc15bdc (v11.15.0-16-gdc15bdc36)
- Wire up properties on Subscription
- Add Subscription properties test

Subscription properties

---

.github/workflows/ci.yml
lib/src/cli/deployapps/baas_client.dart
test/test.dart

Add BaaS setup for all the platforms and create new clusters for Dart/Flutter tests.

BaaS for all platforms

---

.github/workflows/cleanup-clusters.yml

This fixes an issue where apps weren't correctly deleted.

Update cleanup action version

---

lib/src/init.dart

On iOS we used to look up symbols in `DynamicLibrary.process()`, which queries all the loaded shared libraries in the process space (for static linking we should have used `DynamicLibrary.executable()` instead). Now that we link dynamically on iOS we can just provide the direct path to the realm_dart shared library as for the other platforms.

Implement proper DynamicLibrary path lookup for iOS

---

README.md
lib/src/configuration.dart
lib/src/user.dart
test/app_test.dart

Fix small warnings raised by dartdoc tool.

Small API doc fixes

---

lib/src/app.dart
lib/src/native/realm_core.dart
test/app_test.dart

We removed `App.config` but we should at least expose `App.id`.

Expose App.id

---

test/subscription_test.dart

This reverts commit 70c99fa56803da1caca0aac7aa6bd748783b2508.

Fix flexiblesync roundtrip test

---

.github/workflows/ci.yml
CMakePresets.json
scripts/build-ios.sh
scripts/build.bat
src/CMakeLists.txt

build all platforms in a matrix

---

CHANGELOG.md
lib/src/cli/install/install_command.dart

Fixes https://github.com/realm/realm-dart/issues/650

Encode Realm version in install command

---

.github/workflows/ci.yml
.github/workflows/prepare-release.yml
test/app_test.dart
test/configuration_test.dart
test/credentials_test.dart
test/list_test.dart
test/realm_object_test.dart
test/realm_test.dart
test/results_test.dart
test/session_test.dart
test/subscription_test.dart
test/test.dart

This adds tests for M1 macs on a self-hosted runner. I changed the dart test job to be a matrix since all the steps were identical.

Run dart tests on M1

---

.github/workflows/ci.yml
.github/workflows/publish-release.yml

Set up pub.dev credentials based on approach suggested here: https://github.com/dart-lang/pub-dev/issues/5388.
Fixes https://github.com/realm/realm-dart/issues/674.

Publish to pub.dev

---

test/app_test.dart
test/subscription_test.dart

Core fixed https://github.com/realm/realm-core/issues/5543

explicit refresh no longer needed

---

ffigen/pubspec.yaml
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart

- Update realm-core to v12.3.0
- Upgrade ffigen
- Re-generate realm_bindings.dart
- Refactor realm_core.dart to match new bindings

Update core to 12.3.0

---

test/configuration_test.dart

As discussed in https://github.com/realm/realm-core/issues/5364, this should "just work™️".

Reenable some configuration tests

---

flutter/realm_flutter/ios/realm.podspec
generator/lib/src/field_element_ex.dart
lib/src/native/realm_core.dart

On a planning we decided that these tasks are no more relevant:
Closes #692 
Closes #695
Closes #699

Remove Todos - close tasks

---

.github/workflows/ci.yml

Removes action `verify-todos` from ci.yml

Remove TODO check action

---

.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
CHANGELOG.md

This adds the vnext section to the changelog and updates the publish release action to do it automatically next time.

Fix changelog and update release action

---

.github/workflows/ci.yml
.github/workflows/dart-desktop-tests.yml

Example report: https://coveralls.io/builds/51890371
Fixes RDART-567

Enable coverage reports

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yml

These are copy-pasted from the .NET templates.

Add issue templates

---

lib/src/init.dart

Changes how we open shared realm library.
1. First try calling dlopen directly, allowing user to influence searched paths using `DYLD_LIBRARY_PATH`, `LD_LIBRARY_PATH`, etc depending on platform
2. Try to load it form the same directory as the executable, ie. if you compile to an exe you can place the realm lib next to it, and it will work.
3. Try to find a root project from either the placement of the script (Platform.script) and resolve `binary/<platform>/<realm_lib>` from there (ie. load `binary/macos/librealm_dart.so` on macos, etc.)
4. Do what we used to.
This resolves #877

Refactor dlopen search strategy

---

CHANGELOG.md
lib/src/native/realm_bindings.dart
test/list_test.dart

Fix list query bug

---

.vscode/settings.json
CHANGELOG.md
lib/src/native/realm_bindings.dart
test/results_test.dart

Fix results query bug

---

CHANGELOG.md
flutter/realm_flutter/tests/pubspec.yaml
lib/src/native/realm_core.dart
pubspec.yaml
test/realm_test.dart
test/test.dart
test/test.g.dart

Fix property set with subtype

---

lib/src/app.dart

Improve the API documentation about App.deleteUser.
Fixes #880

Improve doc API - deleteUser

---

CHANGELOG.md
generator/lib/src/realm_object_generator.dart

Workaround for analyzer race issue

---

.github/workflows/prepare-release.yml

Fixes https://github.com/realm/realm-dart/issues/656.

Add version input to the prepare release workflow

---

CHANGELOG.md
lib/src/native/realm_core.dart
test/configuration_test.dart

Fixes https://github.com/realm/realm-dart/issues/698

Propagate errors from initial data callback

---

lib/src/cli/metrics/metrics_command.dart

- Use different endpoint for metrics (drop _stage)

Align metrics endpoint with java, js, kotlin and swift

---

CHANGELOG.md
lib/src/user.dart
test/user_test.dart

Throw better api key errors for invalid users

---

lib/src/realm_class.dart

include so that `DisconnectedSyncConfiguration` in reference docs

Include `DisconnectedSyncConfiguration` in reference docs

---

lib/src/configuration.dart
test/configuration_test.dart
test/realm_test.dart

add a test for working encryption

---

CHANGELOG.md
lib/src/subscription.dart
test/subscription_test.dart

- Add removeByType
- Add test of removeByType
Resolve #317 
Resolve #332

Unsubscribe by type

---

CHANGELOG.md

Move `User.functions` for vNext

User.functions changelog

---

.github/workflows/binary-combine-android.yml
.github/workflows/binary-combine-ios.yml
.github/workflows/build-native.yml
.github/workflows/check-changelog.yml
.github/workflows/ci.yml
.github/workflows/dart-desktop-tests.yml
.github/workflows/flutter-desktop-tests.yml

These timeouts should be much higher than what we need, so if we start running into them, we should investigate.

Add timeouts for CI jobs

---

.github/workflows/ci.yml

Android intermittently fails sporadically with this error 
> Running Gradle task 'assembleDebug'...                            130.0s
> ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
> Installing build/app/outputs/flutter-apk/app.apk...              2,869ms
> 
> HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49568/TvuB_2AMsWE=/ws
This is an attempt to fix this.

Fix android CI

---

CHANGELOG.md
lib/src/realm_object.dart
test/backlinks_test.dart

Add missing test and fix bug by using correct metadata from source
Fixes: #1018

Fix issue with accessing properties after traversing a backlink

---

CHANGELOG.md
lib/src/native/realm_bindings.dart
lib/src/user.dart

- Update realm-core to v12.12.0
- Core no longer likes null pointer arguments on atlas function calls

Upgrade realm-core to v12.12.0

---

CHANGELOG.md

Adds changelog for the next release.

vNext Changelog.md

---

CHANGELOG.md
lib/src/configuration.dart
lib/src/native/realm_core.dart
test/configuration_test.dart

Config: Support max number of active versions allowed property.
Fixes #87

Max number of active versions

---

CHANGELOG.md
lib/src/configuration.dart
lib/src/native/realm_core.dart
test/migration_test.dart

Fixes https://github.com/realm/realm-dart/issues/1049

Add support for LocalConfiguration.shouldDeleteIfMigrationNeeded

---

CHANGELOG.md
common/pubspec.yaml
example/pubspec.yaml
ffigen/pubspec.yaml
flutter/realm_flutter/example/pubspec.yaml
flutter/realm_flutter/pubspec.yaml
flutter/realm_flutter/tests/pubspec.yaml
generator/pubspec.yaml
pubspec.yaml

Dart sdk version minimum

---

lib/src/app.dart
lib/src/configuration.dart
lib/src/user.dart

Add links to  [Atlas App Services](https://www.mongodb.com/docs/realm/sdk/flutter/app-services/)

Update API documentation

---

CHANGELOG.md
flutter/realm_flutter/example/pubspec.yaml
flutter/realm_flutter/pubspec.yaml
flutter/realm_flutter/tests/pubspec.yaml

Opened because of this comment https://github.com/realm/realm-dart/pull/1066#discussion_r1052588593.

Bump flutter SDK version to 3.0.3

---

CHANGELOG.md
lib/src/configuration.dart
lib/src/native/realm_bindings.dart
lib/src/native/realm_core.dart
test/client_reset_test.dart

- Update realm-core to v13.2.0
- Return bool from ClientResetError.resetRealm to indicate if reset was initiated or not
- Fill in new metrics required by core

Update realm-core to v13.2.0

---

.github/workflows/flutter-desktop-tests.yml

- Install jq on macos with brew

Install jq on macos

---

CHANGELOG.md
lib/src/realm_class.dart
lib/src/set.dart
test/list_test.dart
test/realm_set_test.dart

handle RealmSet in realm.deleteMany and add a test for it 
fix realm.deleteMany(RealmList) to invoke Core whith ManagedRealmLists only

remove RealmSet.deleteAll()

---

common/lib/src/realm_common_base.dart

Extends the description that `mapTo` can be user on class level.

Update mapTo API doc

---

.github/workflows/prepare-release.yml

Remove default suffix

---

lib/src/cli/atlas_apps/baas_client.dart

Remove permissions from device sync config and move them to the App service rules level.
Related to https://github.com/10gen/baas/pull/8580

Set default rules to Atlas app service

---

CHANGELOG.md
lib/src/configuration.dart
lib/src/native/realm_bindings.dart
lib/src/realm_class.dart
lib/src/session.dart
test/app_test.dart
test/configuration_test.dart
test/list_test.dart
test/realm_set_test.dart
test/realm_test.dart
test/results_test.dart
test/session_test.dart

- Integrate Core unify error handling version -PR https://github.com/realm/realm-core/pull/5441
- Fixed Network error codes changed in PR https://github.com/realm/realm-core/pull/6262
- Added test for `switchUser` - message tests fixed. Fixes #1181

Upgrade core 13.5.0 and fix error messages

---

test/test.dart

remove workaround for compaction file in tests

remove workaround for deleting compaction files in tests

---

.github/workflows/Issue-Needs-Attention.yml
.github/workflows/ci.yml
.github/workflows/cleanup-clusters.yml
.github/workflows/dart-desktop-tests.yml
.github/workflows/flutter-desktop-tests.yml
.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml

Bump to latest green build of realm/ci-actions

Update ci-actions to 043cc5a8446748b823957c6ea4d08e6e495ea996

---

flutter/realm_flutter/tests/test_driver/realm_test.dart
test/realm_value_test.dart

Some tests where only run for Dart

Add forgotten tests to flutter driver tests

---

lib/src/cli/atlas_apps/baas_client.dart
test/credentials_test.dart
test/indexed_test.dart
test/manual_test.dart
test/session_test.dart
test/test.dart

Use a custom `Realm.logger` and `printOnFailure` to only log on test errors.
At the same time increase `logLevel` to `ALL` to get really detailed trace, if a failure do occur

Only log on test failure 

---

.github/workflows/ci.yml
.github/workflows/cleanup-clusters.yml
.github/workflows/create-cluster.yml
.github/workflows/dart-desktop-tests.yml
.github/workflows/flutter-desktop-tests.yml
.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml

See https://github.com/realm/ci-actions/pull/38

Avoid flagging yml file for missing privateapiKey, as opposed to privateApiKey

---

CHANGELOG.md
flutter/realm_flutter/pubspec.yaml
pubspec.yaml

Bump `http` package version ^1.0.0

---

CHANGELOG.md
lib/src/native/realm_core.dart
lib/src/realm_class.dart
lib/src/set.dart
test/realm_set_test.dart
test/test.dart

Support RealmSet.freeze

---

CHANGELOG.md
lib/src/native/realm_bindings.dart
test/embedded_test.dart
test/realm_object_test.dart
test/test.dart

- Upgrade realm-core to v13.17.1
- Fix tests
Fix: #1363

Upgrade realm-core to v13.17.1

---

CHANGELOG.md
lib/src/native/realm_core.dart

Similar fix as for `getAppDirectory`
Bug Introduced by #1316 
Fix #1157

Fix #1157 (should have been a new issue instead of being reopened)

---

generator/lib/src/element.dart
generator/lib/src/error.dart
generator/lib/src/field_element_ex.dart
generator/lib/src/pseudo_type.dart
generator/lib/src/realm_field_info.dart
generator/pubspec.yaml
generator/test/error_test_data/missing_underscore.dart
generator/test/error_test_data/missing_underscore.expected

Pin `analyzer` at ^5.13 and remove use of deprecated members.

Update generator, but stay on analyzer 5.13

---

lib/src/cli/atlas_apps/baas_client.dart
lib/src/native/realm_bindings.dart
lib/src/results.dart
test/indexed_test.dart
test/subscription_test.dart
test/test.dart

Fixes https://github.com/realm/realm-dart/issues/1437

Wait for initial sync to complete before starting the tests

---

CHANGELOG.md
lib/src/app.dart
test/test.dart

Fixes https://github.com/realm/realm-dart/issues/1430

Don't add the ISRG X1 Root on Android

---

CHANGELOG.md
example/bin/myapp.g.dart
flutter/realm_flutter/example/lib/main.g.dart
generator/lib/src/realm_model_info.dart
generator/lib/src/realm_object_generator.dart
generator/test/good_test_data/all_types.expected
generator/test/good_test_data/asymmetric_object.expected
generator/test/good_test_data/embedded_annotations.expected
generator/test/good_test_data/embedded_objects.expected
generator/test/good_test_data/primary_key.expected
generator/test/good_test_data/realm_set.expected
test/backlinks_test.g.dart
test/geospatial_test.g.dart
test/indexed_test.g.dart
test/migration_test.g.dart
test/realm_object_test.g.dart
test/realm_set_test.g.dart
test/realm_value_test.g.dart
test/test.g.dart

Re-fixes https://github.com/realm/realm-dart/issues/1412

Generate only a single lint ignore line

---

CHANGELOG.md
flutter/realm_flutter/linux/CMakeLists.txt

Fixes https://github.com/realm/realm-dart/issues/1381.

Bump the minimum required cmake version to 3.19

---

CHANGELOG.md
lib/src/native/realm_bindings.dart

- Upgrade realm-core to v13.26.0
Fixes : #1481 
Note, not yet exposing new functionality to set base url after initialization!

Upgrade realm-core to v13.26.0

---

.github/workflows/publish-release.yml
.gitignore
CHANGELOG.md
packages/realm/.pubignore
packages/realm_dart/.gitignore
packages/realm_dart/.pubignore
packages/realm_dart/lib/src/native/realm_bindings.dart
packages/realm_generator/.pubignore

Fix: #1568 
- **Update realm-core to v14.2.0-12-g95c6efce8**
- **Update Changelog**

RDART-975: Update core to v14.2.0-12-g95c6efce8

---

.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/cli/metrics/metrics_command.dart
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 2.0.0-alpha.4]

---

.github/workflows/publish-release.yml
CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 2.0.0-alpha.5]

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/native/realm_bindings.dart
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 2.0.0-beta.1]

---

CHANGELOG.md
packages/realm_common/lib/src/realm_types.dart
packages/realm_dart/test/realm_value_test.dart

Fixes https://github.com/realm/realm-dart/issues/1580

RDART-978: Add support RealmValue.fromJson

---

CHANGELOG.md
packages/realm_dart/lib/src/app.dart
packages/realm_dart/lib/src/configuration.dart
packages/realm_dart/lib/src/logging.dart
packages/realm_dart/lib/src/native/realm_bindings.dart
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/lib/src/realm_class.dart
packages/realm_dart/lib/src/scheduler.dart
packages/realm_dart/src/realm_dart_logger.cpp
packages/realm_dart/src/realm_dart_logger.h
packages/realm_dart/src/realm_dart_scheduler.cpp
packages/realm_dart/src/realm_dart_sync.cpp
packages/realm_dart/src/realm_dart_sync.h
packages/realm_dart/test/app_test.dart
packages/realm_dart/test/baas_helper.dart
packages/realm_dart/test/dynamic_realm_test.dart
packages/realm_dart/test/indexed_test.dart
packages/realm_dart/test/realm_logger_test.dart
packages/realm_dart/test/test.dart
pubspec.yaml

- **Update realm-core**
- **Implement and test new logger**
Fixes: #1578

RDART-977: Hierarchical logger

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 2.0.0]

---

packages/CHANGELOG.ejson.md
packages/ejson/lib/src/decoding.dart
packages/ejson/lib/src/encoding.dart
packages/ejson/lib/src/types.dart
packages/ejson/pubspec.yaml
packages/ejson/test/ejson_test.dart
packages/ejson_analyzer/pubspec.yaml
packages/ejson_annotation/pubspec.yaml
packages/ejson_generator/pubspec.yaml
packages/ejson_lint/example/pubspec.yaml
packages/ejson_lint/pubspec.yaml
packages/realm_dart/pubspec.yaml

Fix: #1605 
- **Rename Key to BsonKey to avoid conflict with flutter Key class**
- **Update EJson CHANGELOG**
- **Update EJson version**
- **Update dependency constraints**

RDART-991: Rename Key enum

---

CHANGELOG.md
packages/realm_dart/lib/src/app.dart
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/test/app_test.dart

Fixes https://github.com/realm/realm-dart/issues/1549

RDART-963: Update to new base url

---

.github/workflows/publish-release.yml
packages/realm_dart/test/baas_helper.dart

Follow up on the CR of https://github.com/realm/realm-dart/pull/1586

RDART-987: Schema migration support follow-up

---

CHANGELOG.md

RDART-1008: Update realm-core to v14.15.1

---

.github/workflows/build-native.yml

Don't downgrade to xcode 14.0.1. Not needed and not supported by current action runner.

Don't downgrade xcode

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 2.2.1]

---

CHANGELOG.md
packages/realm_generator/lib/src/realm_model_info.dart
packages/realm_generator/test/good_test_data/private_fields.expected

RDART-1018: Fix badly generated _fromJson

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/cli/metrics/metrics_command.dart
packages/realm_dart/lib/src/native/realm_core.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 2.3.0]

---

.github/workflows/binary-combine-ios.yml
.github/workflows/ci.yml
CHANGELOG.md
packages/realm_dart/CMakePresets.json
packages/realm_dart/dev/lib/src/build.dart
packages/realm_dart/scripts/build-ios.sh

RDART-1039: Drop catalyst support. Flutter doesn't support it

---

CHANGELOG.md
packages/CHANGELOG.ejson.md
packages/ejson/pubspec.yaml
packages/ejson_analyzer/pubspec.yaml
packages/ejson_annotation/pubspec.yaml
packages/ejson_generator/pubspec.yaml
packages/ejson_lint/example/pubspec.yaml
packages/ejson_lint/pubspec.yaml
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 3.1.0]

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/cli/metrics/metrics_command.dart
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 3.2.0]

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/cli/metrics/metrics_command.dart
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 3.3.0]

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 3.4.0]

---

CHANGELOG.md
packages/ejson/pubspec.yaml
packages/ejson_analyzer/pubspec.yaml
packages/ejson_annotation/pubspec.yaml
packages/ejson_generator/pubspec.yaml
packages/ejson_lint/example/pubspec.yaml
packages/ejson_lint/pubspec.yaml
packages/realm_dart/pubspec.yaml

Fixes https://github.com/realm/realm-dart/issues/1778

Bump ejson version

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 3.4.1]

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 20.0.0]

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 3.4.2]

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 20.0.1]

---

CHANGELOG.md
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 20.1.0]

---

.github/workflows/publish-release.yml
CHANGELOG.md
packages/ejson/pubspec.yaml
packages/ejson_analyzer/pubspec.yaml
packages/ejson_annotation/pubspec.yaml
packages/ejson_generator/pubspec.yaml
packages/ejson_lint/example/pubspec.yaml
packages/ejson_lint/pubspec.yaml
packages/realm/example/pubspec.yaml
packages/realm/ios/realm.podspec
packages/realm/macos/realm.podspec
packages/realm/pubspec.yaml
packages/realm_common/pubspec.yaml
packages/realm_dart/lib/src/handles/native/realm_library.dart
packages/realm_dart/pubspec.yaml
packages/realm_dart/src/realm_dart.cpp
packages/realm_generator/pubspec.yaml

[Release 20.1.1]
